/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [,{type: 'autogenerated', dirName: '.'}]
    // But you can create a sidebar manually
    tutorialSidebar: [
      'intro',
      {
        "type": "category",
        "label": "雨云账号",
        "className": "icon-account",
        link: {
          type: 'generated-index',
          // 你可以在这里添加其他配置，比如标题或描述
          title: '雨云账号',
          description: '关于雨云账号的文档。',
          slug: "/category/account"
        },
        "items": [
          {
            "type": "autogenerated",
            "dirName": "account"
          }
        ]
      },
      {
        "type": "category",
        "label": "积分与推广",
        "className": "icon-reward",
        "items": [
          {
            "type": "autogenerated",
            "dirName": "reward"
          }
        ],
        link: {
          type: 'generated-index',
          // 你可以在这里添加其他配置，比如标题或描述
          title: '积分与推广',
          description: '关于积分和推广的文档。',
          slug: "/category/reward"
        }
      },
      {
        "type": "category",
        "label": "虚拟主机RVH",
        "className": "icon-rvh",
        "items": [
          {
            "type": "autogenerated",
            "dirName": "rvh"
          }
        ],
        link: {
          type: 'generated-index',
          // 你可以在这里添加其他配置，比如标题或描述
          title: '虚拟主机',
          description: '关于雨云虚拟主机账号的文档。',
          slug: "/category/rvh"
        }
      },
      {
        "type": "category",
        "label": "云服务器RCS",
        "className": "icon-rcs",
        "items": [
          {
            "type": "autogenerated",
            "dirName": "rcs"
          }
        ],
        link: {
          type: 'generated-index',
          // 你可以在这里添加其他配置，比如标题或描述
          title: '云服务器',
          description: '关于雨云云服务器的文档。',
          slug: "/category/rcs"
        }
      },
      {
        "type": "category",
        "label": "游戏云VPS/面板",
        "className": "icon-rgs",
        "items": [
          {
            "type": "autogenerated",
            "dirName": "rgs"
          }
        ],
        link: {
          type: 'generated-index',
          // 你可以在这里添加其他配置，比如标题或描述
          title: '游戏云',
          description: '关于游戏云的文档。',
          slug: "/category/rgs"
        }
      },
      {
        "type": "category",
        "label": "对象存储",
        "className": "icon-ros",
        "items": [
          {
            "type": "autogenerated",
            "dirName": "ros"
          }
        ],
        link: {
          type: 'generated-index',
          // 你可以在这里添加其他配置，比如标题或描述
          title: '对象存储',
          description: '关于对象存储的文档。',
          slug: "/category/ros"
        }
      },
      {
        "type": "category",
        "label": "域名服务",
        "className": "icon-domain",
        "items": [
          {
            "type": "autogenerated",
            "dirName": "domain"
          }
        ],
        link: {
          type: 'generated-index',
          // 你可以在这里添加其他配置，比如标题或描述
          title: '域名服务',
          description: '关于域名相关的文档。',
          slug: "/category/domain"
        }
      },
      {
        "type": "category",
        "label": "SSL证书中心",
        "className": "icon-ssl",
        "items": [
          {
            "type": "autogenerated",
            "dirName": "ssl"
          }
        ],
        link: {
          type: 'generated-index',
          // 你可以在这里添加其他配置，比如标题或描述
          title: 'SSL证书',
          description: '关于SSL证书的文档。',
          slug: "/category/ssl"
        }
      },"support"
    ]
  ,guide:[{
    "items": [
      {
        "type": "autogenerated",
        "dirName": "guide"
      }
    ]
  },]
};

module.exports = sidebars;
